### ISSUE TITLE
Add AWS Foundational Security Best Practices EMR benchmark

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-aws-compliance#159]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run the EMR benchmark for the AWS Foundational Security Best Practices framework.

**Describe the solution you'd like**
Implement EMR benchmark.

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-aws-compliance/pull/160
