### ISSUE TITLE
Add PCI v3.2.1 SSM benchmark and controls

### ISSUE THREAD

**Issue by sayan133** [turbot/steampipe-mod-aws-compliance#17]
**Is your feature request related to a problem? Please describe.**
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html#pcidss-ssm-1

**Describe the solution you'd like**
Add the Config benchmark and related controls

**Describe alternatives you've considered**

**Additional context**

**Comment by Subhajit97** [comment]
Added in commit https://github.com/turbot/steampipe-mod-aws-compliance/pull/223/commits/37b189b9c688cb21e34adf2b4ac3bb0c505a10f9
