### ISSUE TITLE
Add check for multi-region-cloudtrail-enabled and lambda-dlq-check

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe-mod-aws-compliance#196]
Controls needed for following benchmark
164_308_a_1_ii_d
164_308_a_3_ii_a
164_308_a_6_i
164_308_a_6_ii
164_312_b
164_312_e_2_i

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-aws-compliance/commit/929bbe1b691e652e67c9cc4599ac4479833ac527
