### ISSUE TITLE
HIPAA Benchmark tags not propagating to controls

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-mod-aws-compliance#216]
**Describe the bug**
Querying introspection tables based on tags is not working for new HIPAA controls.

**Steampipe version (`steampipe -v`)**
Example: v0.5.3

**Plugin version (`steampipe plugin list`)**
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.21.0  | aws         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.1.2   | steampipe   |

**To reproduce**
```
steampipe query "select count(*), tags->>'benchmark' from steampipe_control group by 2"
+-------+-----------------------+
| count | ?column?              |
+-------+-----------------------+
| 77    | <null>                |
| 79    | foundational_security |
| 41    | pci                   |
| 113   | cis                   |
+-------+-----------------------+
```

**Expected behavior**
```
+-------+-----------------------+
| count | ?column?              |
+-------+-----------------------+
| 77    | hipaa                 |
| 79    | foundational_security |
| 41    | pci                   |
| 113   | cis                   |
+-------+-----------------------+
```

**Additional context**

**Comment by cbruno10** [comment]
@dboeke HIPAA tags are now available in v0.6 on all HIPAA controls in the form of `hipaa = "true"`. Similarly, for RBI, you can check for those with `rbi_cyber_security = "true"`.
