### ISSUE TITLE
Invalid CIS 1.4 Raport vor network ACL

### ISSUE THREAD

**Issue by wjonkerhulst** [turbot/steampipe-mod-aws-compliance#264]
**Describe the bug**
1) Run steampipe check aws_compliance.benchmark.cis_v140
2) Results in acl-0efe4b9c1c44a2b59 contains 1 rule(s) allowing ingress to port 22 or 3389 from 0.0.0.0/0 or ::/0.
3) See attachment for screenshot ACL. This ACL blocks port 22 and 3889 for ipv4 and ipv6 network
![afbeelding](https://user-images.githubusercontent.com/54948500/130956914-520f4f4e-032d-4488-b448-95cfa2179108.png)

**Steampipe version (`steampipe -v`)**
Example: v0.7.3

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest 0.31.0
| hub.steampipe.io/plugins/turbot/steampipe@latest 0.1.3

**To reproduce**
1) Create ACL as shown in the screenshot
2) Run steampipe check aws_compliance.benchmark.cis_v140

**Expected behavior**
This ACL should pass the rule 'Ensure no Network ACLs allow ingress from 0.0.0.0/0 to remote server administration ports'

**Additional context**

**Comment by rajlearner17** [comment]
@wjonkerhulst sorry for catching up late on this. Could not experiment with this to help on 2nd one. Let me know if you found your own way or expecting an alternative on it. This will help to invest some dedicated time on it.

**Comment by rajlearner17** [comment]
Will recheck based on need. Thanks!!
