### ISSUE TITLE
Support for running CIS kubernetes checks

### ISSUE THREAD

**Issue by seeker815** [turbot/steampipe-mod-aws-compliance#265]
**Is your feature request related to a problem? Please describe.**
I am using steampipe check to run AWS compliance and would like to use Steampipe for Kubernetes Checks as well?

**Describe the solution you'd like**
Support for Kubernetes Compliance checks and a way for steampipe to run them from a pod/host

**Describe alternatives you've considered**
Kube-bench

**Comment by e-gineer** [comment]
Hey @seeker815 ... thanks for asking ... we're actually working on Kubernetes compliance checks as a mod right now :-)

Please see the WIP branches at https://github.com/turbot/steampipe-mod-kubernetes-compliance

Specifically https://github.com/turbot/steampipe-mod-kubernetes-compliance/tree/initial-controls

We'd love your help testing or contributing if you have some time!

**Comment by seeker815** [comment]
Thanks for the quick reply @e-gineer  and will take a look at contributing
