### ISSUE TITLE
Conflict with cis_v140_1_7 and cis_v140_1_12

### ISSUE THREAD

**Issue by ecktom** [turbot/steampipe-mod-aws-compliance#276]
**cis_v140_1_12** triggers for all credentials (password, keys) which where unused for at least 45 days. This rule also includes the root user, even tough it's console access cannot simply get deactivated as described in the remediation for this control. So I suppose if the root user is not excluded here, I'll need to at least login every few weeks to avoid this rule triggering.

**cis_v140_1_7** in contrast triggers, if I login with the root user within the last 90 days

So the CIS Benchmark unfortunately is not very concrete here, does it make sense to exclude the root user in  **cis_v140_1_12**?

**Comment by ecktom** [comment]
I just had another look on **cis_v140_1_12**. Based on the benchmark the audit is

```
aws iam generate-credential-report
aws iam get-credential-report --query 'Content' --output text | base64 -d | cut -d, -f1,4,5,6,9,10,11,14,15,16
```

Based on that it should alarm if:

- For each user having `password_enabled` set to TRUE , ensure `password_last_used_date` is less than 45 days ago.`
- When `password_enabled` is set to TRUE and `password_last_used` is set to No_Information , ensure password_last_changed is less than 45 days ago.

The root user however shows `not_supported` for the `password_enabled`:

```
aws iam get-credential-report --query 'Content' --output text | base64 -d | cut -d, -f1,4,5,6,9,10,11,14,15,16

user,password_enabled,password_last_used,password_last_changed,access_key_1_active,access_key_1_last_rotated,access_key_1_last_used_date,access_key_2_active,access_key_2_last_rotated,access_key_2_last_used_date
<root_account>,not_supported,2021-04-15T06:45:02+00:00,not_supported,false,N/A,N/A,false,N/A,N/A
```

So I don't think it should get considered here

**Comment by rajlearner17** [comment]
@ecktom appreciate the thoughts shared here. CIS interpretation is sometimes challenging to conclude. We have started looking into it, will keep you posted.

**Comment by rajlearner17** [comment]
Hi, @ecktom wanted to have some views expressed here so we make the required change

I understand the ambiguity of showing the `root_account ` in two different threshold days i.e. 90 and 45 days. In cis_v140_1_7 we have considered 90 days (even this is not mentioned exclusively), we referred it from 1.13 in general.

In section `cis_v140_1_12` it's not specifically mentioned to exclude `root_account` from IAM user list, ideally CIS recommends in some cases, in this scenario, should we completely ignore to report root account?  IAM credential report generates the data for root_account. There is definitely a probability of using `root_account` password (password_last_used) and access_keys. Refer [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html)

root_account will have always value **`not_supported `** for `password_enabled` and `password_last_changed`

Will it be fine, if we can ignore `root_account` from the first set of checks and report for the rest of the `password_last_used `and access key use checks?
The change in query is suggested as below, pls review and share your thoughts. 

```
  case
  	-- each user having password_enabled set to TRUE  and password_last_used is null (password never used) and password_last_changed is less than 45 days ago.
    when password_enabled and password_last_used is null and password_last_changed < (current_date - interval '45' day) and user_name != '<root_account>'
      then 'alarm'
```

**Comment by ecktom** [comment]
Hi @rajlearner17, thanks for coming back to this. I was actually wondering how you came up with the 90 days for `cis_v140_1_7` as there is noting specified in the benchmark but I think this is a reasonable time frame.

You're also right, `cis_v140_1_12` does not explicitly recommend to exclude the `root_account`. However implicitly they recommend to look for users having set `password_enabled` to `TRUE` which obviously does not apply for the `root_account`. So I would rather work with `password_enabled` instead of using an exclude like `user_name != '<root_account>'`

I would try to fix this in the AWS plugin. I just had a look and found a suspicious line https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_iam_credential_report.go#L169. If you look at the description it pretends to do the right thing but actually the transform functions does look faulty https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_iam_credential_report.go#L254. If we would return `false` there, `cis_v140_1_12` should be alright I think.

**Comment by rajlearner17** [comment]
@ecktom makes sense will take a look.

**Comment by ecktom** [comment]
> @ecktom makes sense will take a look.

Thanks! Sorry for the confusion, didn't see that part in the plugin when creating this ticket here

**Comment by rajlearner17** [comment]
@ecktom just wanted to update, as we are releasing few items shortly. After a detailed review, we found code wise there is not much to fix, as it addresses current `root_account` behavior properly. We are just marking status as `info` for `root_account` in the `cis_v140_1_12` query, this will help to clear ambiguity
[1] for fields such as `password_enabled` and `password_last_changed`, which AWS API renders as `not_supported` 
[2] will not contradict to `cis_v140_1_7` 
[3] `cis_v140_1_12` (CIS 1.4 > 1.12)  not very specific to `root_account`

**Comment by misraved** [comment]
Closed as a part of - https://github.com/turbot/steampipe-mod-aws-compliance/pull/286 PR
