### ISSUE TITLE
Query vpc_security_group_associated.sql should address distinct clause to filter vpc security groups.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-aws-compliance#282]
**Is your feature request related to a problem? Please describe.**

vpc_security_group_associated.sql is used in the following places 

1. `pci_v321_ec2_3` > `Unused EC2 security groups should be removed` > Query should contain distinct to avoid duplicate data. 
2.` nist_csf_pr_ds_3` >  `control.vpc_security_group_associated` - Though the purpose of the query satisfies the outcome, however, the title `VPC security groups should be associated with at least one ENI` does not match the reason. This should be associated with a new query file.  (New query file change should be in `conformance_pack/vpc.sp`, `nist_csf/function_pr.sp`)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by misraved** [comment]
Closed as apart of - https://github.com/turbot/steampipe-mod-aws-compliance/pull/283 PR
