### ISSUE TITLE
Add AWS Foundational Security Best Practices Elasticsearch benchmark

### ISSUE THREAD

**Issue by sayan133** [turbot/steampipe-mod-aws-compliance#29]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run the Elasticsearch (ES) benchmark for the AWS Foundational Security Best Practices framework.

**Describe the solution you'd like**
Implement ES benchmark.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by sayan133** [comment]
PR merged: https://github.com/turbot/steampipe-mod-aws-compliance/pull/31

**Comment by cbruno10** [comment]
This benchmark is not in `main` yet, re-opening until it's merged back into `main`.
