### ISSUE TITLE
DynamoDB table auto scaling should be enabled fails

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-aws-compliance#312]
**Describe the bug**
DynamoDB table auto scaling should be enabled > **`dynamodb_table_auto_scaling_enabled.sql`** failing with below error
`| | | | ERROR: ValidationException: 1 validation error detected: Value '' at 'serviceNamespace' failed to satisfy constraint: Member must have length greater than or equal to 1`

This issue might have been there, as if you run compliance without any table, it just returns no result

```
+----------+--------+--------+--------+------------+
| resource | status | reason | region | account_id |
+----------+--------+--------+--------+------------+
+----------+--------+--------+--------+------------+
> 
```
**
**Steampipe version (`steampipe -v`)**
AWS Compliance: v0.18.0

**Plugin version (`steampipe plugin list`)**
Example: v0.

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-aws-compliance/pull/319
