### ISSUE TITLE
AWS Foundational Security - Control 1 Foundational Security DynamoDB Incorrectly Interpreting On Demand Capacity Mode

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-mod-aws-compliance#349]
**Describe the bug**
When running control.foundational_security_dynamodb_1 against a table with on demand mode enabled, the resource is still in alarm status.

**Steampipe version (`steampipe -v`)**
Ev0.13.3

**Plugin version (`steampipe plugin list`)**
aws 0.52.0

**To reproduce**
Run control control.foundational_security_dynamodb_1 against DynamoDB tables that have on demand capacity enabled.

**Expected behavior**
Tables with on demand mode enabled should not show as alarm in this control. The description of the control states this as well.

**Comment by misraved** [comment]
@twratl Pleased to see that you are using the Foundational Security controls 👍  .

Thank you for reporting this issue, we will work on it and get the fix in as soon as possible 👍
