### ISSUE TITLE
Split GuardDuty Checks for Foundational Security into Standard GuardDuty Enabled and S3 Logging Enabled

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-mod-aws-compliance#357]
**Is your feature request related to a problem? Please describe.**
Today the check is reporting in alarm if the S3 logging is not enabled. I think it would be better to split this into 2 checks. 1 for regular GuardDuty enabled and one for S3 Logging enabled. 

**Describe the solution you'd like**
Split 1 check into 2.

**Describe alternatives you've considered**
No real alternatives exist except ignoring the finding if S3 logging is not enabled but regular GuardDuty is.

**Additional context**
Existing logic is here.
(https://github.com/turbot/steampipe-mod-aws-compliance/blob/main/query/guardduty/guardduty_enabled.sql)

**Comment by cbruno10** [comment]
Hey @twratl , thanks for suggestion! Looking at the control for [GuardDuty.1](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-guardduty-1), it recommends enabling GuardDuty in the region, but I'm not sure if it specifically mentions S3.

@rajlearner17 Do you recall why we check for S3 logging? Is it based on a detail in the [Config rule](https://docs.aws.amazon.com/config/latest/developerguide/guardduty-enabled-centralized.html) associated with that control?

**Comment by rajlearner17** [comment]
@twratl Thanks for the suggestion
@cbruno10 Investigating this and the thought process behind the same. Will keep posted

**Comment by rajlearner17** [comment]
@cbruno10 @twratl After checking in detail, as suggested by @twratl, there is no need of checking S3 logging, which seems to be an additional unwanted check. I can't recall the circumstances during that time. While working 100s of compliance controls, which differ slightly in some places, we might have used this one. We will be fixing this soon for release.
