### ISSUE TITLE
The is_logging column of the aws_cloudtrail_trail table returns <null> when value is 'true'

### ISSUE THREAD

**Issue by cmd-ctrl-freq** [turbot/steampipe-mod-aws-compliance#366]
**Describe the bug**
The value for the `is_logging` column seems to be incorrect. I noticed this when the aws compliance mod alarmed incorrectly on [this query](https://hub.steampipe.io/mods/turbot/aws_compliance/queries/cloudtrail_multi_region_trail_enabled).

**Steampipe version (`steampipe -v`)**
steampipe version 0.12.0

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------------+---------+--------------------------------------------------------------+
| Name                                             | Version | Connections                                                  |
+--------------------------------------------------+---------+--------------------------------------------------------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.46.0  | meta_connection,REDACTED,REDACTED,REDACTED |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.2.0   | steampipe                                                    |
+--------------------------------------------------+---------+--------------------------------------------------------------+

**To reproduce**
run `select * from aws_cloudtrail_trail`, or a more targeted query to pull back information about whether a cloudtrail is currently logging, and compare that data to AWS CLI output or console information. Here's an example CLI command `aws  cloudtrail get-trail-status --name MyTargetTrail --region us-east-1`

**Expected behavior**
I expect the information about the logging status of a trail to be consistent across steampipe/CLI/Console.

**Additional context**
None

**Comment by rajlearner17** [comment]
@cmd-ctrl-freq Appreciate trying out Steampipe
Sorry to see this reported inconsistent; er are checking this one to replicate and will update you soon. 
If you wish, feel free to send PR as well

**Comment by misraved** [comment]
Hello @cmd-ctrl-freq, while digging into the above issue, we realised that the issue is deep-rooted in the AWS plugin.

Thank you for reporting this, I have opened another issue in the AWS plugin [here](https://github.com/turbot/steampipe-plugin-aws/issues/957).

Please let us know if you run into more issues.

**Comment by misraved** [comment]
hello @cmd-ctrl-freq , the issue has now been resolved and it is available in `aws` plugin version `0.62.0`. Please let us know if you still face issues. 👍
