### ISSUE TITLE
Lambda control have query bug and does not handle custom runtimes

### ISSUE THREAD

**Issue by megaproaktiv** [turbot/steampipe-mod-aws-compliance#370]
**Describe the bug**
With doing 
```bash
steampipe check benchmark.foundational_security --export=check.html --export=check.nunit3.xml
```

You get nil values in nunit3:

```xml
<value><nil></value>
```

And errors in html report:
Lambda - 1 Lambda function policie...
Error: " relation "aws_lambda_function" does not exist (SQLSTATE 42P01)

**Steampipe version (`steampipe -v`)**
steampipe version 0.13.6

**Plugin version (`steampipe version 0.13.6`)**
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.56.0  | aws         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.2.0   | steampipe   |
+--------------------------------------------------+---------+-------------+
**To reproduce**

```bash
steampipe check benchmark.foundational_security --export=check.html --export=check.nunit3.xml
grep "<value><nil></value>"
```

**Expected behavior**
- grep does not find any occurance
- control "foundational_security_lambda_2" should give no error

**Additional context**
Solution part 1:

in All "query/lambda/lambda_function_*" 
change last line to

```sql
  "aws_lambda_function";
```

Solution part 2:

Handle the "nil" for field runtime if lambdas have custom runtimes in query/lambda/lambda_function_use_latest_runtime.sql.

```sql
  case
    when (( runtime in ('nodejs14.x', 'nodejs12.x', 'nodejs10.x', 'python3.8', 'python3.7', 'python3.6', 'ruby2.5', 'ruby2.7', 'java11', 'java8', 'go1.x', 'dotnetcore2.1', 'dotnetcore3.1') ) OR runtime is NULL) then 'ok'
    else 'alarm'
  end as status,
```

**Comment by rajlearner17** [comment]
@megaproaktiv Appreciate using Steampipe
Exciting catch, thank you!! 
We will test this and plan the release.

**Comment by rajlearner17** [comment]
[Depends](https://github.com/turbot/steampipe-plugin-aws/pull/956)
