### ISSUE TITLE
[EC2.21] Network ACLs should not allow ingress from 0.0.0.0/0 to port 22 or port 3389

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-mod-aws-compliance#404]
**Describe the bug**
This control fails even when we are blocking 22/3339 from 0.0.0.0/0 in higher priority rules. Screenshot below.

![image](https://user-images.githubusercontent.com/134659/171645182-84416918-6de6-4d29-9189-57b8696a27d3.png)

**Steampipe version (`steampipe -v`)**
0.14.5

**Plugin version (`steampipe plugin list`)**
0.60.0

**To reproduce**
Add rules that block the ports but leave an ANY/ANY rule open at a lower priority.

**Expected behavior**
This control should pass as 22/3389 are properly being blocked.

**Comment by cbruno10** [comment]
@rajlearner17 Sometimes the documentation for Config rules is missing steps or checks they perform. Do you know what the [nacl-no-unrestricted-ssh-rdp Config rule](https://docs.aws.amazon.com/config/latest/developerguide/nacl-no-unrestricted-ssh-rdp.html) evaluates to for the scenario provided by @twratl ? In general, we usually follow the Config rule's evaluation criteria and try to match that in our control.

**Comment by rajlearner17** [comment]
@cbruno10 you may be right as NACL_NO_UNRESTRICTED_SSH_RDP does not specify, not able to sharply recollect, what we might have checked during its development. We need to re-check how the AWS config rule evaluates this case. 

The [remediation](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-21) directs to  [NACLs settings](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html), which shows the NACL evaluation based in `Rule number`. But You are right; better I check how a similar case is evaluated in the AWS config rule then conclude.

**Comment by rajlearner17** [comment]
@cbruno10 @twratl 
Tracking back- sorry for the delayed response. 

I guess AWS config rule NACL_NO_UNRESTRICTED_SSH_RDP is also not validating the rule number priority as per testing. I hope the query meets config requirements. 

![image](https://user-images.githubusercontent.com/26873346/173542363-c2a3e204-ce9a-47d0-aecb-5ba265f0a05d.png)


![image](https://user-images.githubusercontent.com/26873346/173541386-c64b5243-6933-451a-ab5d-6018c4df2a38.png)

**Comment by cbruno10** [comment]
Thanks @rajlearner17 for checking against the Config rule!

@twratl To explain a bit more, when implementing AWS' Config rules, we usually follow what AWS specifies in their rule, and when it's ambiguous, we see how the rule behaves (like the case above). This is so if users are already using Config rules, or following any of the AWS conformance pack recommendations/controls, our results will be consistent with those results.

So in this case, as @rajlearner17 had mentioned, we will not update our query as this would be a deviation. For A workaround, I'd suggest that you can locally modify that query in particular, or add a new query/control that will be run along with the other controls as part of the benchmark you're running.
