### ISSUE TITLE
Steampipe 0.15 Dashboards no longer working

### ISSUE THREAD

**Issue by rkiller** [turbot/steampipe-mod-aws-compliance#425]
**Describe the bug**
Installed steampipe a few days ago and everything worked, but then upgraded to 0.15 and suddenly the dashboards stopped working. CLI works fine.

**Steampipe version (`steampipe -v`)**
v0.15.0

![Screen Shot 2022-06-24 at 2 03 54 PM](https://user-images.githubusercontent.com/4185175/175667324-be0817a2-b597-411a-90f6-ba18b668ef03.png)

**Comment by judell** [comment]
Hey @rkiller, sorry for the glitch. Questions:

- Which dashboard (and which version of it)?

- Only that one or others too?

**Comment by rkiller** [comment]
Sorry @judell ... I'm new to this :) 

dashboard aws v0.66.0

All the dashboards in this mod are not working for me. I've reinstalled etc etc but they're not working.

**Comment by judell** [comment]
True for other mods as well?

Anything to see if you run `STEAMPIPE_LOG_LEVEL=trace steampipe dashboard` and then check `~/.steampipe/logs`?

**Comment by rkiller** [comment]
I only have the AWS mod installed. Not sure what to look for in the logs, but nothing _seems_ to stand out...

**Comment by rkiller** [comment]
Just installed steampipe-mod-aws-perimeter and having the same issue

**Comment by judell** [comment]
OK. Let's see if @MichaelBurgess can suss out what's happening from your JS console errors. Meanwhile would you mind trying a mod based on a different plugin, e.g. https://hub.steampipe.io/mods/turbot/net_insights?

**Comment by rkiller** [comment]
Thanks @judell ... installing net mod has the same issue(s).
![Screen Shot 2022-06-24 at 3 06 43 PM](https://user-images.githubusercontent.com/4185175/175699165-68f0e224-032f-4daf-ac43-6c3434992d3d.png)

**Comment by judell** [comment]
I assume you've tried the universal solution to everything?

![image](https://user-images.githubusercontent.com/46509/175700251-6a4d6247-6d6e-4a9f-a822-52c97cc43666.png)

**Comment by rkiller** [comment]
:)))))))) Yes... this problem already occurred yesterday. I've turned 'it' off and on several times already...

**Comment by MichaelBurgess** [comment]
@rkiller sorry to hear you’re having this issue.

I believe you’ve got the old UI assets in the browser still. I believe your browser is caching  the index.html and isn’t pulling them in.

Please can you try a hard refresh (can’t tell from the screenshot why browser you’re using, but in Chrome if you open the dev tools and then press and hold the refresh button

**Comment by MichaelBurgess** [comment]
Sorry, hit the close button by mistake on my phone then!

**Comment by rkiller** [comment]
Of course that was it and so simple. Thanks so much @MichaelBurgess !

**Comment by judell** [comment]
Another variant of "turn it off and on again" !
