### ISSUE TITLE
Update Remediation Steps for cis_v140_1_18

### ISSUE THREAD

**Issue by akumar-99** [turbot/steampipe-mod-aws-compliance#509]
**Describe the bug**
The current mentioned remediation steps are outdated. Now EC2 instances support the change of attached IAM Instance Profile on the fly irrespective of the instance state and no longer require us to re-create a new Instance.

**Comment by cbruno10** [comment]
Hey @akumar-99 , thanks for raising this issue!

For all CIS benchmark and control documentation, we use the text from the official CIS documentation, which includes the documentation for control 1.18 (in CIS v1.4.0 and v1.5.0). We choose not to deviate from the official documentation, as this creates issues with ongoing maintainability and a potential source of confusion for those following the official documentation already today.

However, I also agree that the remediation steps are outdated, so I've just submitted a [proposal](https://workbench.cisecurity.org/sections/1458119/recommendations/2474673) for new audit and remediation steps for this control in the upcoming AWS CIS v1.6.0 benchmark. I think you need a WorkBench account to view it, but hopefully this is a step in the right direction.

I'm closing this issue as we will not modify the documentation for CIS v1.3.0 - v1.5.0 for this control, but hopefully once CIS v1.6.0 comes out, my proposal will be included (in some form) for 1.18.
