### ISSUE TITLE
Add AWS > PCI > Autoscaling, CodeBuild & Config docs.

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-mod-aws-compliance#51]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-aws-compliance/commit/9ecf1afc58bcc54ff2313adaae781340524361e1
