### ISSUE TITLE
Not showing correct status of S3 is publically accessible or not

### ISSUE THREAD

**Issue by lakshyatyagi24** [turbot/steampipe-mod-aws-compliance#523]
**Describe the bug**
I have checked on cloud.steampipe. It shows S3 bucket is not publically accessible but after checking over AWS Console that bucket was publically accessible.

**Steampipe version (`steampipe -v`)**
Using cloud.steampipe

**Plugin version (`steampipe plugin list`)**
v0.52.0

**Comment by cbruno10** [comment]
Hey @lakshyatyagi24 , can you please share what control(s) you're running specifically where you're seeing unexpected results? Sharing the output would be very helpful to us as well so we can understand the issue better.

Also, can you please share how the S3 bucket you're testing is public today, e.g., bucket policy, ACLs, and share any relevant policy statements or ACL configurations (with sensitive info removed)?

Thanks!

**Comment by lakshyatyagi24** [comment]
The output I received on the cloud.steampipe
![image](https://user-images.githubusercontent.com/48288540/201484012-b9a3a16b-eec2-4b05-99a2-68c1826302cc.png)

Showing Publically Accessible in S3 Bucket
![image](https://user-images.githubusercontent.com/48288540/201484030-3a648cf0-d3ad-4d1f-833a-c380f2982620.png)

**Comment by lakshyatyagi24** [comment]
Also can you please assign this to me? I want to work on it.

**Comment by cbruno10** [comment]
@lakshyatyagi24 Sure! I've assigned you to the issue (FYI, for future issues, even if you're not assigned to issue, you're always free to work on it).

Also, in case this is helpful as you start working on the query, I believe this is the AWS Config rule we based the query off of - https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-public-read-prohibited.html. I'm not sure if it only mentioned ACLs at the time when we created the query or if we missed the other checks, but I believe the query should check lock Public Access settings, the bucket policy, and the ACLs.

Hope this helps and thanks for deciding to work on it!

**Comment by misraved** [comment]
Hello @lakshyatyagi24, any updates on this issue? Please let us know if you have any blockers or questions pertaining to this issue 👍.

**Comment by khushboo9024** [comment]
Solved in https://github.com/turbot/steampipe-mod-aws-compliance/pull/548

**Comment by misraved** [comment]
Closed as part of https://github.com/turbot/steampipe-mod-aws-compliance/pull/548
