### ISSUE TITLE
Add new FSBP [AutoScaling.9] control

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-aws-compliance#526]
**Is your feature request related to a problem? Please describe.**

[FSBP [AutoScaling.9] ](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-autoscaling-9)

[AWS Announcement ](https://aws.amazon.com/about-aws/whats-new/2022/09/aws-security-hub-new-security-best-practice-control/)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khushboo9024** [comment]
Added and released as per (https://github.com/turbot/steampipe-mod-aws-compliance/pull/529/files).
