### ISSUE TITLE
DocDB missing from the RDS Logging Enabled

### ISSUE THREAD

**Issue by robh-wirehive** [turbot/steampipe-mod-aws-compliance#547]
The query rds_db_instance_logging_enabled uses the rds_db_instances table, which reports back docdb as one of the Db types in the Database. However the query doesn't account for this type of database, and so always reports error when the 

https://hub.steampipe.io/mods/turbot/aws_compliance/queries/rds_db_instance_logging_enabled

I believe the following code lines can be added to the file

Line 11 
`when engine like 'docdb%' and enabled_cloudwatch_logs_exports ?& array ['audit','profiler'] then 'ok'`

Line 25-26
`when engine like 'docdb%' and enabled_cloudwatch_logs_exports ?& array ['audit','profiler']
    then title || ' ' || engine || ' logging enabled.'`

**Comment by karanpopat** [comment]
Hey @robh-wirehive, thanks for using Steampipe, and thanks for the suggestion.

Looking at the config rule for [rds-logging-enabled](https://docs.aws.amazon.com/config/latest/developerguide/rds-logging-enabled.html), it does not specifically recommend for the DocDB instances as of now.
On trying with AWS Config we get the results as you see below where we had a DocDB instance live with logging disabled, but it wasn't detected by the config rule, but the RDS instance was.

<img width="1159" alt="Screenshot 2023-06-08 at 11 16 52 AM" src="https://github.com/turbot/steampipe-mod-aws-compliance/assets/16674560/20847faa-dd8f-48ca-8adf-f6fb8a4879f7">

**Comment by robh-wirehive** [comment]
Hey @karanpopat - thanks for the research and looking at this. What i am seeing then is a false positive, as Steampipe/AWS sees DocDB as a RDS Instance service, and therefore puts the service as non compliant when logs are not enabled for this resource. So would it be needed that DocDB is not included in this check?

Thanks

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-mod-aws-compliance/pull/660

**Comment by misraved** [comment]
@robh-wirehive we have updated the query to filter out the DocDB resources. Please let us know if this PR fixes your issue 👍 .

Thanks for continuously tracking and testing the changes.

Great collaboration 🎉

**Comment by robh-wirehive** [comment]
Thank you @misraved for the quick turn around :)
