### ISSUE TITLE
ECR tag immutability remediation advice is incorrect, the remediation proposed is for image scanning 

### ISSUE THREAD

**Issue by congon4tor** [turbot/steampipe-mod-aws-compliance#558]
https://github.com/turbot/steampipe-mod-aws-compliance/blob/c7cea47662c03f4cc4a84a17e41872e8ace611dc/foundational_security/docs/foundational_security_ecr_2.md?plain=1#L9

**Comment by cbruno10** [comment]
Hey @congon4tor , nice catch, you are correct our remediation instructions are incorrect!
