### ISSUE TITLE
Support CISv8

### ISSUE THREAD

**Issue by cristiandley** [turbot/steampipe-mod-aws-compliance#559]
Add support to CISv8

Reference: https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-cis-critical-security-controls-v8.html

**Describe alternatives you've considered**
Already use a SOC2 to CISv8 mapping :(

**Comment by cbruno10** [comment]
@cristiandley Are you interested in IG1, IG2, and/or IG3? Also, I'm not familiar with the differences, do you know any key differences between the versions? Thanks!

**Comment by rajlearner17** [comment]
@cristiandley @cbruno10 Audit Manager supports CIS Controls v8 IG1, as we mostly follow the Audit Manager's implementation; I guess this will be good to start with.
![image](https://user-images.githubusercontent.com/26873346/218463473-09e47c83-6803-4005-b093-525343ad0f24.png)

**Comment by misraved** [comment]
Closed as a part of https://github.com/turbot/steampipe-mod-aws-compliance/pull/568
