### ISSUE TITLE
Severity is missing when executing cis Benchmarks 

### ISSUE THREAD

**Issue by semeiner** [turbot/steampipe-mod-aws-compliance#560]
**Describe the bug**
When executing the cis benchmark in the version 1.5 the "severity" is not included in the output file. 

**Steampipe version 
Steampipe v0.18.6

Installed Plugin                                                          | Version | Connections |
hub.steampipe.io/plugins/turbot/aws@latest            | 0.92.2 | aws  
hub.steampipe.io/plugins/turbot/steampipe@latest | 0.6.0   | steampipe 

**To reproduce**
Executing the following command : 
`steampipe check benchmark.cis_v150 --export /home/myoutput.json`

**Expected behavior**
After executing the following command I expect that the severity is included in the myoutput.json
`cat myoutput.json | grep "severity"`

Result: 
 "severity": "",
 "severity": "",
....

The result shows that the severity is empty.

**Additional context**
I tried to execute the command in an "entos rhel fedora" environment.
I get the same error using the official Docker Image from Steampipe.

**Comment by e-gineer** [comment]
We try to follow the exact definition of the benchmarks from the original source. CIS benchmarks don't actually include a severity definition.

What would you expect to see here? How would it be mapped?

**Comment by rajlearner17** [comment]
@semeiner Thanks; just rechecking if this is still an open issue for you. CIS is mapped with `cis_level.`  e.g. `cis_level   = "1" `or `cis_level   = "2"`. We will wait for your response before marking this as closed

**Comment by rajlearner17** [comment]
Marking this as closed, feel free to send feedback, if any.
