### ISSUE TITLE
Add common and tag dimensions across compliance queries

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-aws-compliance#584]
**Is your feature request related to a problem? Please describe.**

Common & tag dimensions will allow the end user with options to render compliance output based on tags key, connection name, account-id & region.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by misraved** [comment]
The new feature has been added in https://github.com/turbot/steampipe-mod-aws-compliance/pull/574
