### ISSUE TITLE
Add/Update AWS Audit Manager > GxP EU Annex 11 controls (2023-05-09)

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-aws-compliance#612]
**Is your feature request related to a problem? Please describe.**

**New Additions**

Benchmark | Control(s)
-- | --
1 Risk Management | config.1 - aws_security_hub
10 Change and Configuration Management | config.1 - aws_security_hub
4.3 Validation - Inventory | required_tags
4.5 Validation - Development Quality | config.1 - aws_security_hub
4.6 Validation - Quality and Performance | config.1 - aws_security_hub
7.1 Data Storage - Damage Protection | opensearch_node_to_node_encryption_check
  | ec2.3 - aws_security_hub

**Controls to remove**

Benchmark | Control(s)
-- | --
1 Risk Management | config_enabled_all_regions - aws_config
10 Change and Configuration Management | config_enabled_all_regions
4.5 Validation - Development Quality | config_enabled_all_regions
4.6 Validation - Quality and Performance | config_enabled_all_regions
7.1 Data Storage - Damage Protection | opensearch_domain_node_to_node_encryption_enabled

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rajlearner17** [comment]
Released https://github.com/turbot/steampipe-mod-aws-compliance/blob/main/CHANGELOG.md#v061-2023-04-07

**Comment by Priyanka-Chatterjee-2000** [comment]
This issue does not require any update as the security hub query controls already exist. Nothing is to be removed or updated.

**Comment by Priyanka-Chatterjee-2000** [comment]
This issue does not require any update as the security hub query controls already exist. Nothing is to be removed or updated to the existing benchmarks.
