### ISSUE TITLE
Add/Update AWS Audit Manager > GxP 21 CFR Part 11 controls (2023-05-09)

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-aws-compliance#613]
**Is your feature request related to a problem? Please describe.**

**New Controls**

Benchmark | Control(s)
-- | --
11_10_a | ec2_volume_inuse_check
11_10_d | iam_role_managed_policy_check
11_10_d | ssm_document_not_public
11_10_d | vpc_sg_open_only_to_authorized_ports
11_10_g | ssm_document_not_public
11_10_g | vpc_sg_open_only_to_authorized_ports
11_10_k | ssm_document_not_public
11_10_k | vpc_sg_open_only_to_authorized_ports

**Removed Controls**

Benchmark | Control(s)
-- | --
aws_config | ebs_attached_volume_delete_on_termination_enabled
aws_config | iam_policy_custom_no_assume_role
aws_config | vpc_security_group_allows_ingress_authorized_ports
aws_config | vpc_security_group_allows_ingress_authorized_ports
aws_config | vpc_security_group_allows_ingress_authorized_ports

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-aws-compliance/pull/638
