### ISSUE TITLE
Bug: Remove deprecated/obsolete AWS Foundational Security Best Practices Benchmark Controls

### ISSUE THREAD

**Issue by sfunkernw** [turbot/steampipe-mod-aws-compliance#667]
Some AWS Foundational Benchmark Controls were removed, see https://docs.aws.amazon.com/securityhub/latest/userguide/doc-history.html

For example, https://hub.steampipe.io/mods/turbot/aws_compliance/controls/control.foundational_security_ec2_27?context=benchmark.foundational_security/benchmark.foundational_security_ec2 should be removed because it got removed from the officiel benchmark in 20. July 2020 (see EC2.27 is retired in benchmark history above) with the comment “Security Hub has retired EC2.27 - Running EC2 Instances should not use key pairs, a former control in the AWS Foundational Security Best Practices (FSBP) standard.”

It would make imho a lot of sense to remove the "retired" controls from the benchmark of the compliance mod as well.

**Comment by rajlearner17** [comment]
@sfunkernw, Thanks for using Steampipe!

We appreciate your notifying us; we will include further checking our monthly update cycle. 

Cheers! 👍
