### ISSUE TITLE
Add AWS PCI S3 Docs. 

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-mod-aws-compliance#67]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-aws-compliance/commit/c33c5b4b56179d73d43caec6edd42d7e9ce6413f
