### ISSUE TITLE
Managed AWS IAM Policies Trigger During a Steampipe Scan Since They are not Attached To Role Or Group

### ISSUE THREAD

**Issue by cybrfghtr** [turbot/steampipe-mod-aws-compliance#709]
**Is your feature request related to a problem? Please describe.**

When running a steampipe AWS compliance scan, over 1000 alerts trigger because the default AWS managed policies are in use or attached to a role or group.  We discussed this with the steampipe team in Slack.  

https://turbot-community.slack.com/archives/C02NMCM2QKE/p1690432150150639
https://turbot-community.slack.com/archives/C02NMCM2QKE/p1691505605799529?thread_ts=1690432150.150639&cid=C02NMCM2QKE

**Describe the solution you'd like**

We would like a way for any and all AWS managed policies to be excluded from findings.  

**Describe alternatives you've considered**

For now, we can filter in a CSV / Excel document.  Any new scans and any new managed AWS policies would have to be filtered out again.

**Additional context**

The CC1.3 aws compliance scan lists out ALL of the AWS managed IAM policies that are not assigned to an IAM role.  There are over 1100 AWS managed IAM policies.  This can is for a very small organization so most of the AWS IAM policies are not in use.  As a result, this compliance scan is marking nearly all of the AWS managed IAM policies as a finding since they are not associated with an IAM role.  What would be the recommendation since we will never use all of the AWS managed policies?  And after trying, I found out that you can not just attach ALL of the AWS IAM policies to a single IAM role that will never be used.
Here are some examples:
CC1.3 COSO Principle 3: Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives
aws_compliance.control.iam_managed_policy_attached_to_roleIAM AWS managed policies should be attached to IAM roleThis control checks if all AWS managed policies specified in the list of managed policies are attached to the AWS Identity and Access Management (IAM) role. The rule is non compliant if an AWS managed policy is not attached to the IAM role.
AmazonMachineLearningCreateOnlyAccess not attached to IAM role.arn:aws:iam::aws:policy/AmazonMachineLearningCreateOnlyAccess
CC1.3 COSO Principle 3: Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives
aws_compliance.control.iam_managed_policy_attached_to_roleIAM AWS managed policies should be attached to IAM roleThis control checks if all AWS managed policies specified in the list of managed policies are attached to the AWS Identity and Access Management (IAM) role. The rule is non compliant if an AWS managed policy is not attached to the IAM role.
PowerUserAccess not attached to IAM role.arn:aws:iam::aws:policy/PowerUserAccess
CC1.3 COSO Principle 3: Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives
aws_compliance.control.iam_managed_policy_attached_to_roleIAM AWS managed policies should be attached to IAM roleThis control checks if all AWS managed policies specified in the list of managed policies are attached to the AWS Identity and Access Management (IAM) role. The rule is non compliant if an AWS managed policy is not attached to the IAM role.
ReadOnlyAccess not attached to IAM role.arn:aws:iam::aws:policy/ReadOnlyAccess
CC1.3 COSO Principle 3: Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives
aws_compliance.control.iam_managed_policy_attached_to_roleIAM AWS managed policies should be attached to IAM roleThis control checks if all AWS managed policies specified in the list of managed policies are attached to the AWS Identity and Access Management (IAM) role. The rule is non compliant if an AWS managed policy is not attached to the IAM role.
AWSCloudFormationReadOnlyAccess not attached to IAM role.arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess

**Comment by rajlearner17** [comment]
@cybrfghtr Thanks for the issue!

Adding the [slack reference ](https://turbot-community.slack.com/archives/C02NMCM2QKE/p1690432150150639)

We will check it and provide further updates.

**Comment by khushboo9024** [comment]
@cybrfghtr Thanks for bringing this out, this issue need to introduce variables to provide the required `policyArns` as  input parameters. Currently, our compliance module lacks this capability. For the time being, we're going to close this issue since introducing this feature isn't part of our immediate plans. However, we may look into implementing it later on. Please  feel free to reopen this issue if you have further concerns or queries.

Thanks !!
