### ISSUE TITLE
Enhance README.md with Emojis for Clarity

### ISSUE THREAD

**Issue by SOBANEJAZ** [turbot/steampipe-mod-aws-compliance#720]
**Issue Description**:
I would like to contribute to this repository by enhancing the README.md for improved clarity and aesthetics. My suggestion is to add emojis to the existing headings in the README to make it more visually appealing and user-friendly.

**Proposed Emojis for Headings**:

1. **Getting Started **🚀
  I. **Installation** 📦
  II. **Usage** 💡
  III. **Credentials** 🔐
  IV.** Configuration** ⚙️
2. **Contributing** 🤝
I believe that adding emojis to the headings will not only make the documentation more engaging but also help readers quickly identify and understand the content of each section.

**Please assign this issue to me for the hacktoberfest. :)**

**Comment by e-gineer** [comment]
Thanks - but we prefer the README doc a bit more boring without the extra emojis 😅 

We also try to keep our format consistent across the many mods / plugins, so consider carefully structural changes like this before implementing.

**Comment by SOBANEJAZ** [comment]
ok, so I should submit pull request.

**Comment by e-gineer** [comment]
No - sorry if I was unclear - I'm saying above that we don't want this change.

**Comment by SOBANEJAZ** [comment]
you mean I should submit on PR.
OK
