### ISSUE TITLE
Support for Swiss GDPR - nFADP compliance

### ISSUE THREAD

**Issue by anjuls** [turbot/steampipe-mod-aws-compliance#729]
**Is your feature request related to a problem? Please describe.**
There is a recent compliance being implemented in Swiss region for data protection. 
https://www.kmu.admin.ch/kmu/en/home/facts-and-trends/digitization/data-protection/new-federal-act-on-data-protection-nfadp.html

**Describe the solution you'd like**
Need a compliance check covering nFADP. 

**Describe alternatives you've considered**
Not considered, I love steampipe :)

**Additional context**

**Comment by rajlearner17** [comment]
@anjuls Thanks for your interest in Steampipe! 👍 

I appreciate you directed us to a new compliance. As I checked, a recent AWS article is published [here](https://aws.amazon.com/blogs/alps/using-aws-in-light-of-the-new-swiss-data-protection-act/) 

Until now, there is no information from AWS on how this is implemented using AWS config controls. We follow AWS implementation from [AWS Audit Manager Supported Framework ](https://docs.aws.amazon.com/audit-manager/latest/userguide/GDPR.html). Whenever there will be a change or update for this new compliance, we will be ready to bring that into our compliance bucket.

Cheers!

**Comment by bigdatasourav** [comment]
Hey, @anjuls, closing the issue for now; please feel free to re-open it if you want to share anything. Thanks!
