### ISSUE TITLE
FALSE-Negative and False-Positive for AWS Compliance > Remove unused Secrets Manager secrets

### ISSUE THREAD

**Issue by the-cloud-ninja** [turbot/steampipe-mod-aws-compliance#751]
Describe the bug

Mod: AWS Compliance Mod
Control: 3 Remove unused Secrets Manager secrets / aws_compliance.control.foundational_security_secretsmanager_3

Issue:
Return values are wrong. Secret that were retrieved today or in the last few days are marked with Alarm, however other secrets that werent received for 500 days+ are marked as OK.

Try the CLI with JQ to compare:

aws secretsmanager list-secrets --region eu-central-1 --profile YOURAWSPROFILE \ | jq .SecretList \ | jq 'map(.LastAccessedDate |= if type == "number" then strftime("%Y-%m-%d") else "<never>" end)' \ | jq 'map(select(.LastAccessedDate <= "2024-2-2" or .LastAccessedDate == "<never>"))' \ | jq -r 'map([.LastAccessedDate, .Name] | @tsv) | join("\n")'

Steampipe version (steampipe -v)
Steampipe v0.21.4
aws@latest 0.129.0

To reproduce
steampipe check aws_compliance.control.foundational_security_secretsmanager_3

Compare results with AWS CLI:

aws secretsmanager list-secrets --region eu-central-1 --profile YOURAWSPROFILE \ | jq .SecretList \ | jq 'map(.LastAccessedDate |= if type == "number" then strftime("%Y-%m-%d") else "<never>" end)' \ | jq 'map(select(.LastAccessedDate <= "2024-2-2" or .LastAccessedDate == "<never>"))' \ | jq -r 'map([.LastAccessedDate, .Name] | @tsv) | join("\n")'

Example FALSE POSITIVE (secret retrieved today, marked as alarm):

Secret "DockerCredentials", last used Yesterday (January 31st 2024)
        { "ARN": "arn:aws:secretsmanager:eu-central-1:11111111111:secret:DockerCredentials", "Name": "DockerCredentials", "LastChangedDate": 1706706820.497, "LastAccessedDate": 1706659200.0, "Tags": [ { "Key": "service", "Value": "prod - DMS" } ], "SecretVersionsToStages": { "500xxxxxxxxx": [ "AWSCURRENT" ], "650xxxxxxxxxx": [ "AWSPREVIOUS" ] }, "CreatedDate": 1706706795.483 }

**Example FALSE-NEGATIVE (retrieved 666 days ago, marked as OK) **
Secret "user-secret", last used 666 days ago (April 6th 2022)

        { "ARN": "arn:aws:secretsmanager:eu-central-1:11111111:secret:user-secret", "Name": "user-secret", "LastChangedDate": 1633435259.956, "LastAccessedDate": 1649203200.0, "Tags": [], "SecretVersionsToStages": { "cfbxxxxxxxxxxxxx": [ "AWSCURRENT" ] }, "CreatedDate": 1633435259.913 },

Expected behavior
List of all Secrets unused 90 days+

**Comment by the-cloud-ninja** [comment]
Additonal Infos:

**Control from command line:**
`steampipe check aws_compliance.control.foundational_security_secretsmanager_3`

**Result:**
`3 Remove unused Secrets Manager secrets .......................................................... 1 / 41 [==========]
  ALARM: DockerCredentials not used recently. ............................................. eu-central-1 1111111111
  OK   : user-secret recently used. ............................. eu-central-1 11111111`


**Steampile Query however:**

`steampipe` query "select name, last_accessed_date from aws_secretsmanager_secret;"`

**Result:**

`+------------------------------------------+---------------------------+
| name                                     | last_accessed_date        |
+------------------------------------------+---------------------------+
| DockerCredentials                     | 2024-01-31T01:00:00+01:00 |
| user-secret                                       | 2022-04-06T02:00:00+02:00 |
+------------------------------------------+---------------------------+`

So, the Query brings the correct result. The control hower is false-positive and false-negative.

**Comment by khushboo9024** [comment]
Thank you, @the-cloud-ninja, for identifying this issue. We have incorporated the necessary corrections in the [PR](https://github.com/turbot/steampipe-mod-aws-compliance/pull/752) and are prepared to proceed with the release as soon as possible. In the meantime, we invite you to test the PR and share any feedback or observations you might have.

**Comment by the-cloud-ninja** [comment]
Thank you so much @khushboo9024  for this very quick response. 

cheers
Markus

**Comment by the-cloud-ninja** [comment]
This does the trick! Brilliant! False-Negatives and False-Positives were gone with your Query replacement.
