### ISSUE TITLE
Change control title of aws_compliance.control.foundational_security_es_2 to "Elasticsearch domains should not be public accessible"

### ISSUE THREAD

**Issue by semeiner** [turbot/steampipe-mod-aws-compliance#760]
AWS has changed the control: "2 Amazon Elasticsearch Service domains should be in a VPC" to "Elasticsearch domains should not be public accessible" because Elasticsearch can't be deployed outside an VPC. Therefore, the control title should be renamed to  "Elasticsearch domains should not be public accessible".

AWS changed the control title as well, this can be reviewed in den Security Hub documentation: (entry at 16th, November 2023)
https://docs.aws.amazon.com/securityhub/latest/userguide/controls-change-log.html

Thanks in advance
Sven

**Comment by khushboo9024** [comment]
@semeiner Thanks for raising this issue, we will publish the changes ASAP.

**Comment by Liltonar** [comment]
@khushboo9024 Thank you for updating the titles.
But I notices that Lambda 2 also changes, but is missing in your pull request.
https://docs.aws.amazon.com/securityhub/latest/userguide/lambda-controls.html#lambda-2
