### ISSUE TITLE
False-Positive: control.foundational_security_ecr_1 does not consider enhanced scanning method

### ISSUE THREAD

**Issue by the-cloud-ninja** [turbot/steampipe-mod-aws-compliance#762]
**Describe the bug**
The control control.foundational_security_ecr_1 checks, if the ECR repo has scan on push enabled. If disabled, the control will consider this as ALARM. 

However, if the ECR enhanced scanning is enabled for the whole region, **ALL** repositories are scanned by this mechanism anyway, see https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-enhanced.html

**Steampipe version (`steampipe -v`)**
v0.21.7

**Plugin version (`steampipe plugin list`)**
aws 0.131.0

**To reproduce**

First, let's use steampipe and the specific control:

`steampipe check aws_compliance.control.foundational_security_ecr_1
`
1 ECR private repositories should have image scanning configured ......... HIGH 10 / 10 [==========]
   ALARM: MyRepo scan on push disabled. .......................... eu-central-1 MYACCOUNT

OK, now let's crosscheck this with the AWS CLI:

`aws ecr describe-repositories --region eu-central-1 —profile MYACCOUNT`

{
    "repositories": [
        {
            "repositoryArn": "arn:aws:ecr:eu-central-1:MYACCOUNT:repository/MyRepo",
            "registryId": "MYACCOUNT",
            "repositoryName": „MyRepo,
            "repositoryUri": "MYACCOUNT.dkr.ecr.eu-central-1.amazonaws.com/MyRepo",
            "createdAt": 1690385025.197,
            "imageTagMutability": "MUTABLE",
            "imageScanningConfiguration": {
                "scanOnPush": **false**
            },
            "encryptionConfiguration": {
                "encryptionType": "AES256"
            }
   
    ]
}

OK, it seems to be that the Alarm seems to be correct. However, I know, that we use the Enhanced scanning feature to scan always all Repos. Let's check how it look like:

`aws ecr get-registry-scanning-configuration --region eu-central-1 —profile MYACCOUNT`
{
    "registryId": "MYACCOUNT",
    "scanningConfiguration": {
        "scanType": "ENHANCED",
        "rules": [
            {
                "scanFrequency": "CONTINUOUS_SCAN",
                "repositoryFilters": [
                    {
                        "filter": "*",
                        "filterType": "WILDCARD"
                    }
                ]
            }
        ]
    }
}

Result: Enhanced Scanning is enabled. OK. Lets go further. Next we check the repo from above, if we do have any scan results...

`aws ecr describe-image-scan-findings --repository-name "MyRepo" --image-id imageDigest="sha256:123456789“`

{
    "imageScanFindings": {
        "enhancedFindings": [
            {
                "awsAccountId": "MYACCOUNT",
                "description": "FasterXML jackson-databind 2.x before 2.9.10.8 mishandles the interaction between serialization gadgets and typing, related to org.apache.commons.dbcp2.datasources.PerUserPoolDataSource.",
                "findingArn": "arn:aws:inspector2:eu-central-1: MYACCOUNT:finding/11111111“,
                "firstObservedAt": 1690389036.512,
                "lastObservedAt": 1708128538.925,
                "packageVulnerabilityDetails": {
                    "cvss": [
                        {
                            "baseScore": 8.1,
                            "scoringVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
                            "source": "NVD",
                            "version": "3.1"
                        }
                    ],
 
            },
############ many more findings cutted ########

So, to conclude:
The control control.foundational_security_ecr_1 checks, if the ECR repo has scan on push enabled. If disabled, the control will consider this as ALARM. It will not be considered, if the quiet new enhanced scanning feature is enabled or not.

**Expected behavior**
Please do a crosscheck, if enhanced scanning is enabled. If YES >> this alarm shall SKIP instead of raising an alarm.

cheers
Markus

**Comment by khushboo9024** [comment]
@the-cloud-ninja Thanks for raising this issue, we are working on it and will try to publish ASAP.
