### ISSUE TITLE
column reference "region" is ambiguous (SQLSTATE 42702) running control.foundational_security_ecr_1

### ISSUE THREAD

**Issue by semeiner** [turbot/steampipe-mod-aws-compliance#801]
**Describe the bug**
When running the foundational_security benchmark, we are always getting the error **"column reference "region" is ambiguous (SQLSTATE 42702)"**  at the control `control.foundational_security_ecr_1` 

**Powerpipe version (`powerpipe -v`)**
Example: v0.1.3

**Steampipe version (`steampipe -v`)**
Example: v0.22.0

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest | 0.136.1 | aws
hub.steampipe.io/plugins/turbot/steampipe@latest | 0.10.0 | steampipe

**To reproduce**
executing the following command: 
`steampipe check benchmark.foundational_security --export foundational_security_{ACCOUNT_NAME}_2024-06-20.csv --progress=false`

**Expected behavior**
The error doesn't occur running the benchmark. 

**Additional context**
The Benchmark is executed in a container using the latest turbot/steampipe image.

**Comment by khushboo9024** [comment]
Hi @semeiner,
Sorry for the radio silence on this issue. Could you please answer the following questions to make it easier for us to replicate/debug this issue?:
- Which container are you using to run the Benchmark?
- Did you try using the `powerpipe` command? Does it throw the same error?
Thanks.

**Comment by semeiner** [comment]
Hello @khushboo9024, 

thank you for the response, using powerpipe command fixed the issue. 
I tried running the benchmark inside a fargate container. 
 
I appreciate the help!
