### ISSUE TITLE
elbv2 Load balancer integrated with wafv2 Rule Check

### ISSUE THREAD

**Issue by shyam0904a** [turbot/steampipe-mod-aws-compliance#832]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently checks are made to check if waf fail open is configured but there are cases where waf fail open is set to true but does not have a waf web acl associated with it.

**Describe alternatives you've considered**
A new control that can check for elb/elbv2 for its association with wafv2 

**Additional context**
nil

**Comment by khushboo9024** [comment]
@shyam0904a Apologies for the delay in responding. We have updated our query [elb_application_lb_waf_enabled](https://github.com/turbot/steampipe-mod-aws-compliance/pull/840) to correctly evaluate results when a WAF Web ACL is associated. Please let us know if you have any other concerns.

Thanks

**Comment by misraved** [comment]
Fix available in `v1.1.1` mod version - https://github.com/turbot/steampipe-mod-aws-compliance/blob/main/CHANGELOG.md#v111-2024-10-30
