### ISSUE TITLE
ELB application load balancers should have Web Application Firewall (WAF) enabled

### ISSUE THREAD

**Issue by nbhamare-godaddy** [turbot/steampipe-mod-aws-compliance#837]
**Describe the bug**
ELB application load balancers should have Web Application Firewall (WAF) enabled

**Powerpipe version (`powerpipe -v`)**
v0.4.3

**Steampipe version (`steampipe -v`)**
v0.23.5

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------------+---------+-------------+
| Installed                                        | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 1.0.0   | aws         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 1.0.0   | steampipe   |
+--------------------------------------------------+---------+-------------+

**To reproduce**
Steps to reproduce the behavior.

Use a AWS account with ELB and WAF integration enabled.
Scan the AWS account and observe that Powerpipe identify following issue. 
ELB application load balancers should have Web Application Firewall (WAF) enabled

**Expected behavior**
Since the WAF is enabled. It should not show this as a Alarm.

**Comment by khushboo9024** [comment]
Hi @nbhamare-godaddy 

Thank you for raising this bug. We were able to reproduce the issue and have raised a [PR](https://github.com/turbot/steampipe-mod-aws-compliance/pull/840) with a fix. Could you please check from your end and let us know if it works for you?

Thanks.
