### ISSUE TITLE
unique resources for SSM constrols

### ISSUE THREAD

**Issue by m-rieke** [turbot/steampipe-mod-aws-compliance#842]
**Is your feature request related to a problem? Please describe.**
After running powerpipe we are creating automatic reports out of the outcome. For keeping the results as small as possible we are focussing on the controls in combination with resource.
We observed that in SSM controls findings are reported with the same resource and we have to parse the corresponding instance id from description.

**Describe the solution you'd like**
I would like to simply access the instance id for automatic reporting. 

A suggestion would be for ssm_2:
Instead of resource:
     python3-urllib3.amd64
Also report the instanceid in the resource field
     python3-urllib3.amd64/i-1234fce2334412

**Describe alternatives you've considered**
Currently the only way is to parse the instance id from description.

**Comment by khushboo9024** [comment]
@m-rieke Apologies for the delay in responding. Could you please specify which control or query you are using so we can further investigate the issue?

**Comment by misraved** [comment]
Hello @m-rieke ,

We haven’t received a response in a while, so we’re going to close this issue for now. If this is still a concern or if you have additional details to share, please don’t hesitate to reopen the issue, and we’ll be happy to assist you further.

Thank you for your understanding, and we appreciate your contributions!!
