### ISSUE TITLE
EBS encryption by default should be enabled

### ISSUE THREAD

**Issue by nbhamare-godaddy** [turbot/steampipe-mod-aws-compliance#845]
**Describe the bug**
In an AWS account when no EBS volumes are present the scan shows "us-east-1 EBS encryption by default disabled."

**Powerpipe version (`powerpipe -v`)**
Powerpipe v0.4.3

**Steampipe version (`steampipe -v`)**
Steampipe v0.23.5

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------------+---------+-------------+
| Installed                                        | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 1.0.0   | aws         |
| hub.steampipe.io/plugins/turbot/azure@latest     | 1.0.0   | azure       |
| hub.steampipe.io/plugins/turbot/azuread@latest   | 1.0.0   | azuread     |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 1.0.0   | steampipe   |
+--------------------------------------------------+---------+-------------+
**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
Scan an AWS account with no EBS volumes.
Open scan result and observe that scan shows "us-east-1 EBS encryption by default disabled."

**Expected behavior**
The scan should show no vulnerability.

**Comment by khushboo9024** [comment]
@nbhamare-godaddy Thanks for raising this issue. We reviewed the CIS document on our end and found that it specifies that EBS volume encryption should be enabled in all regions. However, it does not state that EBS volumes must exist in a particular region. Encrypting data at rest reduces the likelihood of unintentional exposure. Let me know if this answers your question.

Thanks!!

**Comment by cbruno10** [comment]
@nbhamare-godaddy For more info on EBS encryption by default (which CIS is asking users to check for, like @khushboo9024 had mentioned), please see https://docs.aws.amazon.com/ebs/latest/userguide/encryption-by-default.html.

I'm closing this issue as I believe our CIS checks are correct, but if you have any other questions, please feel free to re-open this issue, thanks!
