### ISSUE TITLE
Add AWS Foundational Security Best Practices SecretsManager benchmark

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-mod-aws-compliance#86]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run the SecretsManager benchmark for the AWS Foundational Security Best Practices framework.

**Describe the solution you'd like**
Implement SecretsManager benchmark.

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-aws-compliance/pull/92
